-- Create the scores table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_address TEXT NOT NULL,
    score INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- Drop any existing policies (safe to do with IF EXISTS)
DROP POLICY IF EXISTS "Public read access for leaderboard" ON public.scores;
DROP POLICY IF EXISTS "Service role insert access" ON public.scores;

-- Create policies
CREATE POLICY "Public read access for leaderboard"
ON public.scores
FOR SELECT
TO public
USING (true);

CREATE POLICY "Service role insert access"
ON public.scores
FOR INSERT
TO service_role
WITH CHECK (true);